### ISSUE TITLE
Activate/Select exact match in search list

### ISSUE THREAD

**Issue by antis81** [lxqt/lxqt-runner#193]
##### Expected Behavior
Select an exact match e.g. "code", "libreoffice", …). 

##### Current Behavior
Am I the only one who by accident opens other applications when writing e.g. "code"? (In my case CoBang QR reader is selected instead of vscode -> both set up by *.desktop files).
An especially annoying example is "libreoffice" (shorthands don't do good like e.g. "libre", "office" - or even "LO"). Entry is always last in search list (after "LibreOffice Base/Calc/Impress/Writer/…").

Note: Having "recent used" disabled for my setup. 

##### Possible Solution
Show exact matches first, followed by "best match"/"recent used" maybe?

##### System Information
LXQt 0.17

**Comment by tsujan** [comment]
The comments are also searched and that's intentional (the user may not remember an app's name). As for LibreOffice, `libreoffice-startcenter.desktop` comes last because of its name. The sorting is alphabetical.

Any kind of sorting may feel appropriate for some and "annoying" for others. You can use the keys `Home` and `End` as well as `Up` and `Down`. Since your selection is preserved, there's no real issue.

**Comment by tsujan** [comment]
I opened https://github.com/lxqt/lxqt-runner/issues/194
